### PR TITLE
Move all manifests into namespaced folders

### PR DESCRIPTION
**Pull request by jb3**
This PR prevents us adding a bunch of folders to the root of the Kubernetes repository by moving manifests into folders based on the namespace they are deployed to.

### CODE REVIEW

**Comment by lemonsaurus** [comment]
Screenshot of the new folder structure would be nice in a PR like this.

**Comment by jb3** [comment]
image

**Comment by lemonsaurus** [comment]
seems nice. 👍🏼 

guessing this will break a bunch of stuff, and there will be a bunch of related PRs to solve those things? Do you have a plan for the order that everything will need to be merged?

**Comment by jb3** [comment]
Yeah, all services that clone the repo will need an update. My plan is to merge this first and then open a PR on all repos that need the change – since it's just a path update I'll bypass policy-bot.

**Review by jchristgit — APPROVED** [review]
Excellent, Joe.

Like that Daft Punk song:

🎵 Merge it, push it, break it, fix it, faster 🎶

**Pull request merged**
